package com.jly.purejiandan.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig readFreshDaoConfig;

    private final ReadFreshDao readFreshDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readFreshDaoConfig = daoConfigMap.get(ReadFreshDao.class).clone();
        readFreshDaoConfig.initIdentityScope(type);

        readFreshDao = new ReadFreshDao(readFreshDaoConfig, this);

        registerDao(ReadFresh.class, readFreshDao);
    }
    
    public void clear() {
        readFreshDaoConfig.getIdentityScope().clear();
    }

    public ReadFreshDao getReadFreshDao() {
        return readFreshDao;
    }

}
