package com.jly.purejiandan.db;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "READ_FRESH".
 */
public class ReadFresh {

    private Integer freshId;

    public ReadFresh() {
    }

    public ReadFresh(Integer freshId) {
        this.freshId = freshId;
    }

    public Integer getFreshId() {
        return freshId;
    }

    public void setFreshId(Integer freshId) {
        this.freshId = freshId;
    }

}
